### ISSUE TITLE
관리자 애그리거트 정의

### ISSUE THREAD

**Issue by stemmmm** [atwoz-dev/atwoz_server#10]
### 기능 설명
- 관리자 애그리거트 정의

### To-Do's
- [x] Admin 루트 엔티티 정의
- [x] Email 값 타입 정의
- [x] Password 값 타입 정의
- [ ] 테스트 코드 작성
