### ISSUE TITLE
하트 트랜잭션 애그리거트 정의

### ISSUE THREAD

**Issue by hainho** [atwoz-dev/atwoz_server#11]
### 기능 설명
하트 트랜잭션 애그리거트에서 하트 충전 및 사용 검증 및 기록에 대한 책임을 담당하도록 정의

### To-Do's
- [x] 하트 트랜잭션 루트 애그리거트 정의
- [x] 변화량 값 타입 정의
- [x] 잔액 값 타입 정의
- [x] 하트 충전, 사용 메서드 정의
- [x] 하트 잔액 검증 메서드 정의
- [x] 테스트 코드 작성
