### ISSUE TITLE
하트 사용 정책 애그리거트 정의

### ISSUE THREAD

**Issue by hainho** [atwoz-dev/atwoz_server#22]
### 기능 설명
- 하트 사용 정책 애그리거트를 정의

### To-Do's
- [x] 하트 사용 정책 애그리거트
- [x] 하트 사용 타입
- [x] 사용 타입 -> 트랜잭션 타입 맵퍼
- [x] 테스트 코드
