### ISSUE TITLE
프로필 이미지 삭제 구현

### ISSUE THREAD

**Issue by Kong-TaeHyeon** [atwoz-dev/atwoz_server#27]
### 기능 설명
프로필 이미지 단건 삭제 기능 추가.
### To-Do's
- [ ] Repo 에서 해당 프로필 이미지 엔티티 삭제(Hard Delete)
- [ ] S3 에서 해당 URL과 연결된 파일 삭제
- [ ] 테스트 케이스 작성
