### ISSUE TITLE
취미 애그리거트 및 멤버취미 도메인 정의

### ISSUE THREAD

**Issue by Kong-TaeHyeon** [atwoz-dev/atwoz_server#32]
### 기능 설명
취미 애그리거트와 이에 따른 연관 관계를 위한 멤버-취미 도메인을 멤버 애그리거트에 정의.
### To-Do's
- [ ] Hobby 도메인 정의
- [ ] MemberHobby 도메인 정의
- [ ] 테스트 코드 작성
