### ISSUE TITLE
Git 컨벤션 정리

### ISSUE THREAD

**Issue by stemmmm** [atwoz-dev/atwoz_server#5]
### To-Do's
- [x] Git 컨벤션 Wiki에 정리
- [x] PR 템플릿 수정
- [x] 이슈 템플릿 수정
